// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://btptsqprylnktkceyuad.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ0cHRzcXByeWxua3RrY2V5dWFkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIxMjkyMzUsImV4cCI6MjA1NzcwNTIzNX0.QqYHky_CMko60nE-nhEUVCcJ5mkyNmRvrphU-eHNKAA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);